export const GET_ITEMS_REQUESTED = "GET_ITEMS_REQUESTED";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";
export const GET_FILTERED_ITEMS_BY_AGE = "GET_FILTERED_ITEMS_BY_AGE";
export const GET_FILTERED_ITEMS_BY_COST = "GET_FILTERED_ITEMS_BY_COST";
export const REMOVE_COST_FILTER = "REMOVE_COST_FILTER";